name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get go mod info
        id: gomod
        uses: pawndev/go-modfile-information@v1.0.0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^${{ steps.gomod.outputs.go_version }}'
      - name: Build
        run: |
          go mod download
          go build -v .
