name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: '^1.20'
        id: go
      - uses: actions/checkout@v3
      - name: Build
        run: |
          go mod download
          go build -v .
